catalogHost="catalog-service"
cartHost="cart-service"
recommendHost="recommendation-service"
currencyHost="currency-service"
shippingHost="shipping-service"
checkoutHost="checkout-service"
adHost="ads-service"
currencyTimeout=3.0
catalogTimeout=3.0
cartTimeout=3.0
shippingTimeout=3.0
recommendationTimeout=3.0
adTimeout=3.0
checkoutTimeout=3.0

[ballerina.observe]
tracingEnabled=true
tracingProvider="jaeger"

[ballerinax.jaeger]
agentHostname="jaeger"
agentPort=55680
samplerType="const"
samplerParam=1.0
reporterFlushInterval=2000
reporterBufferSize=1000
